services:
  qdrant:
    image: qdrant/qdrant:v1.12.0
    container_name: qdrant-vector-db
    ports:
      - "6333:6333" # REST API and Dashboard
      - "6334:6334"  # GRPS port
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped
    environment:
      # Setting off telemetry
      - QDRANT__TELEMETRY_DISABLED=true
    deploy:
      resources:
        limits:
          memory: 1G
